config = dict()
config["cuda_devices"] = True
config["labels"] = (0, 1, 2, 3)
# config["labels"] = (1,) # change label to train
#config["model_file"] =os.path.join(r'F:\experiment\othermodel\BraTS2018_NvNet-master', os.path.abspath("runs\single_label_{}_dice.h5".format(config["labels"][0])))
config["initial_learning_rate"] = 3e-4
config["batch_size"] = 2
config["validation_batch_size"] = 2
config["image_shape"] = (128, 128, 128)
config["activation"] = "relu"
config["normalizaiton"] = "group_normalization"
config["mode"] = "trilinear"
config["n_labels"] = len(config["labels"])
config["all_modalities"] = ["t1", "t1ce", "flair", "t2"]
config["training_modalities"] = config["all_modalities"]  # change this if you want to only use some of the modalities
config["nb_channels"] = len(config["training_modalities"])
config["input_shape"] = tuple([config["batch_size"]] + [config["nb_channels"]] + list(config["image_shape"]))
config["loss_k1_weight"] = 0.1
config["loss_k2_weight"] = 0.1
config["random_offset"] = True # Boolean. Augments the data by randomly move an axis during generating a data
config["random_flip"] = True  # Boolean. Augments the data by randomly flipping an axis during generating a data
config["result_path"] = "./checkpoint_models/"
config["saved_model_file"] = None
config["overwrite"] = False  # If True, will create new files. If False, will use previously written files.
config["L2_norm"] = 1e-5
config["patience"] = 2
config["lr_decay"] = 0.7
config["VAE_enable"] = False  # Boolean. If True, will enable the VAE module.
